#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const bashrc = path.resolve(path.join(__dirname, "config", "bash-config"));
const bash_dest = path.resolve(path.join(process.env.HOME, ".bashrc"));

let src = fs.readFileSync(bashrc, "utf-8");
let dest = fs.readFileSync(bash_dest, "utf-8");

let dest_match = dest.match(/OSH_THEME=\"(.*)\"/);

if (dest_match) {
  let replaced = `OSH_THEME="${dest_match[1]}"`;
  let replacer = `OSH_THEME="agnoster"`;
  dest = dest.replace(replaced, replacer);
}
dest += `\n\n${src}`;

fs.writeFileSync(bash_dest, dest);
